name: Aggregate
on: [workflow_dispatch, push]
jobs:
  aggregate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build data.json
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require("fs");

            const metaphors = fs.readdirSync("./data")
              .filter((filename) => /\.json$/.test(filename))
              .map((filename) => {
                const body = JSON.parse(fs.readFileSync(`./data/${filename}`, "utf8"));
                return body;
              });

            fs.writeFileSync("./data.json", JSON.stringify(metaphors));
      - name: Commit data.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Build data.json"
